export const ALL_GENRES = [
  'Pop', 'Hip-Hop', 'Rap', 'R&B', 'Soul',
  'Rock', 'Alternative', 'Indie', 'Punk', 'Metal',
  'Country', 'Folk', 'Latin', 'K-Pop',
  'Electronic', 'Jazz', 'Jam Band', 'Poetry',
]

export const SUGGESTED_ARTISTS = [
  // Pop
  { name: 'Taylor Swift', genre: 'Pop' },
  { name: 'Billie Eilish', genre: 'Pop' },
  { name: 'Olivia Rodrigo', genre: 'Pop' },
  { name: 'Dua Lipa', genre: 'Pop' },
  { name: 'Harry Styles', genre: 'Pop' },
  { name: 'Sabrina Carpenter', genre: 'Pop' },
  { name: 'Beyoncé', genre: 'Pop' },
  { name: 'Ariana Grande', genre: 'Pop' },
  { name: 'Lana Del Rey', genre: 'Pop' },
  { name: 'Charli XCX', genre: 'Pop' },
  { name: 'Chappell Roan', genre: 'Pop' },
  { name: 'Troye Sivan', genre: 'Pop' },
  // Hip-Hop
  { name: 'Kendrick Lamar', genre: 'Hip-Hop' },
  { name: 'Drake', genre: 'Hip-Hop' },
  { name: 'Tyler, the Creator', genre: 'Hip-Hop' },
  { name: 'Travis Scott', genre: 'Hip-Hop' },
  { name: 'J. Cole', genre: 'Hip-Hop' },
  { name: 'Kanye West', genre: 'Hip-Hop' },
  { name: 'MF DOOM', genre: 'Hip-Hop' },
  { name: 'JID', genre: 'Hip-Hop' },
  { name: '21 Savage', genre: 'Hip-Hop' },
  { name: 'Future', genre: 'Hip-Hop' },
  // Rap
  { name: 'Eminem', genre: 'Rap' },
  { name: 'Nicki Minaj', genre: 'Rap' },
  { name: 'Lil Wayne', genre: 'Rap' },
  { name: 'Mac Miller', genre: 'Rap' },
  { name: 'Tupac', genre: 'Rap' },
  { name: 'Nas', genre: 'Rap' },
  { name: 'Jay-Z', genre: 'Rap' },
  { name: 'A$AP Rocky', genre: 'Rap' },
  { name: 'Joey Bada$$', genre: 'Rap' },
  { name: 'Denzel Curry', genre: 'Rap' },
  // R&B
  { name: 'SZA', genre: 'R&B' },
  { name: 'The Weeknd', genre: 'R&B' },
  { name: 'Frank Ocean', genre: 'R&B' },
  { name: 'Daniel Caesar', genre: 'R&B' },
  { name: 'Steve Lacy', genre: 'R&B' },
  { name: 'Summer Walker', genre: 'R&B' },
  { name: 'Erykah Badu', genre: 'R&B' },
  { name: 'Kehlani', genre: 'R&B' },
  // Soul
  { name: 'Stevie Wonder', genre: 'Soul' },
  { name: 'Marvin Gaye', genre: 'Soul' },
  { name: 'Amy Winehouse', genre: 'Soul' },
  { name: 'Aretha Franklin', genre: 'Soul' },
  { name: 'Al Green', genre: 'Soul' },
  { name: 'Otis Redding', genre: 'Soul' },
  { name: 'Leon Bridges', genre: 'Soul' },
  // Rock
  { name: 'Radiohead', genre: 'Rock' },
  { name: 'Arctic Monkeys', genre: 'Rock' },
  { name: 'Fleetwood Mac', genre: 'Rock' },
  { name: 'The Beatles', genre: 'Rock' },
  { name: 'Led Zeppelin', genre: 'Rock' },
  { name: 'Pink Floyd', genre: 'Rock' },
  { name: 'Queen', genre: 'Rock' },
  { name: 'Nirvana', genre: 'Rock' },
  { name: 'The Strokes', genre: 'Rock' },
  { name: 'David Bowie', genre: 'Rock' },
  { name: 'The Rolling Stones', genre: 'Rock' },
  // Alternative
  { name: 'Gorillaz', genre: 'Alternative' },
  { name: 'The 1975', genre: 'Alternative' },
  { name: 'Glass Animals', genre: 'Alternative' },
  { name: 'Cage the Elephant', genre: 'Alternative' },
  { name: 'Twenty One Pilots', genre: 'Alternative' },
  { name: 'The Smashing Pumpkins', genre: 'Alternative' },
  { name: 'Pixies', genre: 'Alternative' },
  { name: 'Weezer', genre: 'Alternative' },
  // Indie
  { name: 'Phoebe Bridgers', genre: 'Indie' },
  { name: 'Hozier', genre: 'Indie' },
  { name: 'Tame Impala', genre: 'Indie' },
  { name: 'Bon Iver', genre: 'Indie' },
  { name: 'Mitski', genre: 'Indie' },
  { name: 'Clairo', genre: 'Indie' },
  { name: 'Vampire Weekend', genre: 'Indie' },
  { name: 'The National', genre: 'Indie' },
  { name: 'Japanese Breakfast', genre: 'Indie' },
  { name: 'Boygenius', genre: 'Indie' },
  { name: 'Alex G', genre: 'Indie' },
  { name: 'Beach House', genre: 'Indie' },
  // Punk
  { name: 'The Clash', genre: 'Punk' },
  { name: 'Green Day', genre: 'Punk' },
  { name: 'Blink-182', genre: 'Punk' },
  { name: 'My Chemical Romance', genre: 'Punk' },
  { name: 'Turnstile', genre: 'Punk' },
  { name: 'Paramore', genre: 'Punk' },
  { name: 'The Ramones', genre: 'Punk' },
  // Metal
  { name: 'Metallica', genre: 'Metal' },
  { name: 'Tool', genre: 'Metal' },
  { name: 'Deftones', genre: 'Metal' },
  { name: 'System of a Down', genre: 'Metal' },
  { name: 'Gojira', genre: 'Metal' },
  { name: 'Slipknot', genre: 'Metal' },
  { name: 'Black Sabbath', genre: 'Metal' },
  // Country
  { name: 'Zach Bryan', genre: 'Country' },
  { name: 'Noah Kahan', genre: 'Country' },
  { name: 'Morgan Wallen', genre: 'Country' },
  { name: 'Chris Stapleton', genre: 'Country' },
  { name: 'Kacey Musgraves', genre: 'Country' },
  { name: 'Tyler Childers', genre: 'Country' },
  { name: 'Sturgill Simpson', genre: 'Country' },
  { name: 'Johnny Cash', genre: 'Country' },
  { name: 'Willie Nelson', genre: 'Country' },
  // Folk
  { name: 'Iron & Wine', genre: 'Folk' },
  { name: 'Fleet Foxes', genre: 'Folk' },
  { name: 'Joni Mitchell', genre: 'Folk' },
  { name: 'Nick Drake', genre: 'Folk' },
  { name: 'Elliott Smith', genre: 'Folk' },
  { name: 'Adrianne Lenker', genre: 'Folk' },
  { name: 'Bob Dylan', genre: 'Folk' },
  { name: 'Simon & Garfunkel', genre: 'Folk' },
  { name: 'Sufjan Stevens', genre: 'Folk' },
  // Latin
  { name: 'Bad Bunny', genre: 'Latin' },
  { name: 'Peso Pluma', genre: 'Latin' },
  { name: 'Rosalía', genre: 'Latin' },
  { name: 'Karol G', genre: 'Latin' },
  { name: 'Rauw Alejandro', genre: 'Latin' },
  { name: 'Feid', genre: 'Latin' },
  { name: 'J Balvin', genre: 'Latin' },
  { name: 'Shakira', genre: 'Latin' },
  // K-Pop
  { name: 'BTS', genre: 'K-Pop' },
  { name: 'BLACKPINK', genre: 'K-Pop' },
  { name: 'NewJeans', genre: 'K-Pop' },
  { name: 'Stray Kids', genre: 'K-Pop' },
  { name: 'aespa', genre: 'K-Pop' },
  { name: 'TWICE', genre: 'K-Pop' },
  { name: 'LE SSERAFIM', genre: 'K-Pop' },
  // Electronic
  { name: 'Fred again..', genre: 'Electronic' },
  { name: 'Aphex Twin', genre: 'Electronic' },
  { name: 'Daft Punk', genre: 'Electronic' },
  { name: 'Flume', genre: 'Electronic' },
  { name: 'ODESZA', genre: 'Electronic' },
  { name: 'Jamie xx', genre: 'Electronic' },
  { name: 'Disclosure', genre: 'Electronic' },
  { name: 'Caribou', genre: 'Electronic' },
  { name: 'Four Tet', genre: 'Electronic' },
  // Jazz
  { name: 'Miles Davis', genre: 'Jazz' },
  { name: 'John Coltrane', genre: 'Jazz' },
  { name: 'Kamasi Washington', genre: 'Jazz' },
  { name: 'Norah Jones', genre: 'Jazz' },
  { name: 'Robert Glasper', genre: 'Jazz' },
  { name: 'Thelonious Monk', genre: 'Jazz' },
  { name: 'Nina Simone', genre: 'Jazz' },
  // Jam Band
  { name: 'Grateful Dead', genre: 'Jam Band' },
  { name: 'Phish', genre: 'Jam Band' },
  { name: 'Widespread Panic', genre: 'Jam Band' },
  { name: 'Goose', genre: 'Jam Band' },
  { name: 'Billy Strings', genre: 'Jam Band' },
  { name: 'Khruangbin', genre: 'Jam Band' },
  { name: 'The Allman Brothers Band', genre: 'Jam Band' },
  { name: 'String Cheese Incident', genre: 'Jam Band' },
  // Poetry
  { name: 'Rupi Kaur', genre: 'Poetry' },
  { name: 'Amanda Gorman', genre: 'Poetry' },
  { name: 'Ocean Vuong', genre: 'Poetry' },
  { name: 'Mary Oliver', genre: 'Poetry' },
  { name: 'Lang Leav', genre: 'Poetry' },
  { name: 'Atticus', genre: 'Poetry' },
  { name: 'Warsan Shire', genre: 'Poetry' },
  { name: 'Pablo Neruda', genre: 'Poetry' },
  { name: 'Sylvia Plath', genre: 'Poetry' },
  { name: 'Edgar Allan Poe', genre: 'Poetry' },
]
