export const themes = {
  default: {
    id: 'default',
    name: 'Default',
    description: 'Clean and modern',
    fontFamily: "'Inter', system-ui, sans-serif",
    fontSize: '1.5rem',
    fontWeight: '400',
    lineHeight: '1.6',
    fontStyle: 'normal',
    letterSpacing: '0',
    textAlign: 'center',
    backgroundColor: '#FAF9F6',
    textColor: '#2C2C2C',
    secondaryColor: '#8B8B8B',
  },
  away: {
    id: 'away',
    name: 'Away',
    description: 'Status message vibes',
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    fontSize: '1.25rem',
    fontWeight: '400',
    lineHeight: '1.7',
    fontStyle: 'normal',
    letterSpacing: '0',
    textAlign: 'left',
    backgroundColor: '#EFEFEF',
    textColor: '#333333',
    secondaryColor: '#666666',
  },
  notebook: {
    id: 'notebook',
    name: 'Notebook',
    description: 'Written for yourself',
    fontFamily: "'EB Garamond', Georgia, serif",
    fontSize: '1.625rem',
    fontWeight: '400',
    lineHeight: '1.7',
    fontStyle: 'italic',
    letterSpacing: '0.01em',
    textAlign: 'left',
    backgroundColor: '#FDF8F3',
    textColor: '#1a1a1a',
    secondaryColor: '#6B6B6B',
  },
  darkroom: {
    id: 'darkroom',
    name: 'Darkroom',
    description: 'Quiet and inward',
    fontFamily: "'Inter', system-ui, sans-serif",
    fontSize: '1.5rem',
    fontWeight: '400',
    lineHeight: '1.6',
    fontStyle: 'normal',
    letterSpacing: '0.02em',
    textAlign: 'center',
    backgroundColor: '#1C1C1E',
    textColor: '#F5F5F5',
    secondaryColor: '#8E8E93',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Almost nothing',
    fontFamily: "'Inter', system-ui, sans-serif",
    fontSize: '1.125rem',
    fontWeight: '400',
    lineHeight: '1.6',
    fontStyle: 'normal',
    letterSpacing: '0',
    textAlign: 'center',
    backgroundColor: '#FFFFFF',
    textColor: '#6B6B6B',
    secondaryColor: '#A0A0A0',
  },
  poster: {
    id: 'poster',
    name: 'Poster',
    description: 'Bold and declarative',
    fontFamily: "'Work Sans', system-ui, sans-serif",
    fontSize: '2rem',
    fontWeight: '700',
    lineHeight: '1.3',
    fontStyle: 'normal',
    letterSpacing: '-0.02em',
    textAlign: 'center',
    backgroundColor: '#FAF9F6',
    textColor: '#1a1a1a',
    secondaryColor: '#666666',
  },
}

export const themeList = Object.values(themes)
