export const themes = {
  default: {
    id: 'default',
    name: 'Default',
    description: 'Clean and modern',
    fontFamily: "'Inter', system-ui, sans-serif",
    fontSize: '1.5rem',
    fontWeight: '400',
    lineHeight: '1.6',
    fontStyle: 'normal',
    letterSpacing: '0',
    textAlign: 'center',
    backgroundColor: '#FAF9F6',
    textColor: '#2C2C2C',
    secondaryColor: '#8B8B8B',
  },
  away: {
    id: 'away',
    name: 'Away',
    description: 'Status message vibes',
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    fontSize: '1.25rem',
    fontWeight: '400',
    lineHeight: '1.7',
    fontStyle: 'normal',
    letterSpacing: '0',
    textAlign: 'left',
    backgroundColor: '#EFEFEF',
    textColor: '#333333',
    secondaryColor: '#666666',
  },
  notebook: {
    id: 'notebook',
    name: 'Notebook',
    description: 'Written for yourself',
    fontFamily: "'EB Garamond', Georgia, serif",
    fontSize: '1.625rem',
    fontWeight: '400',
    lineHeight: '1.7',
    fontStyle: 'italic',
    letterSpacing: '0.01em',
    textAlign: 'left',
    backgroundColor: '#FDF8F3',
    textColor: '#1a1a1a',
    secondaryColor: '#6B6B6B',
  },
  darkroom: {
    id: 'darkroom',
    name: 'Darkroom',
    description: 'Quiet and inward',
    fontFamily: "'Inter', system-ui, sans-serif",
    fontSize: '1.5rem',
    fontWeight: '400',
    lineHeight: '1.6',
    fontStyle: 'normal',
    letterSpacing: '0.02em',
    textAlign: 'center',
    backgroundColor: '#1C1C1E',
    textColor: '#F5F5F5',
    secondaryColor: '#8E8E93',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Almost nothing',
    fontFamily: "'Inter', system-ui, sans-serif",
    fontSize: '1.125rem',
    fontWeight: '400',
    lineHeight: '1.6',
    fontStyle: 'normal',
    letterSpacing: '0',
    textAlign: 'center',
    backgroundColor: '#FFFFFF',
    textColor: '#6B6B6B',
    secondaryColor: '#A0A0A0',
  },
  poster: {
    id: 'poster',
    name: 'Poster',
    description: 'Bold and declarative',
    fontFamily: "'Work Sans', system-ui, sans-serif",
    fontSize: '2rem',
    fontWeight: '700',
    lineHeight: '1.3',
    fontStyle: 'normal',
    letterSpacing: '-0.02em',
    textAlign: 'center',
    backgroundColor: '#FAF9F6',
    textColor: '#1a1a1a',
    secondaryColor: '#666666',
  },
  handwritten: {
    id: 'handwritten',
    name: 'Handwritten',
    description: 'Warm and personal',
    fontFamily: "'Caveat', cursive",
    fontSize: '1.875rem',
    fontWeight: '500',
    lineHeight: '1.5',
    fontStyle: 'normal',
    letterSpacing: '0.01em',
    textAlign: 'left',
    backgroundColor: '#FBF8F3',
    textColor: '#3D3226',
    secondaryColor: '#8B7355',
  },
  neon: {
    id: 'neon',
    name: 'Neon',
    description: 'Electric and glowing',
    fontFamily: "'Space Mono', monospace",
    fontSize: '1.5rem',
    fontWeight: '700',
    lineHeight: '1.5',
    fontStyle: 'normal',
    letterSpacing: '0.05em',
    textAlign: 'center',
    backgroundColor: '#0A0A0A',
    textColor: '#FF006E',
    secondaryColor: '#FF006E',
    textShadow: '0 0 10px rgba(255, 0, 110, 0.8), 0 0 20px rgba(255, 0, 110, 0.5), 0 0 30px rgba(255, 0, 110, 0.3)',
  },
  vinyl: {
    id: 'vinyl',
    name: 'Vinyl',
    description: 'Warm nostalgia',
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    fontSize: '1.375rem',
    fontWeight: '400',
    lineHeight: '1.7',
    fontStyle: 'normal',
    letterSpacing: '0.02em',
    textAlign: 'center',
    backgroundColor: '#E8D5C4',
    textColor: '#5C3D2E',
    secondaryColor: '#8B6F47',
  },
  typewriter: {
    id: 'typewriter',
    name: 'Typewriter',
    description: 'Raw and unfiltered',
    fontFamily: "'Courier Prime', 'Courier New', monospace",
    fontSize: '1.25rem',
    fontWeight: '400',
    lineHeight: '1.8',
    fontStyle: 'normal',
    letterSpacing: '0.05em',
    textAlign: 'left',
    backgroundColor: '#F5F1E8',
    textColor: '#2B2B2B',
    secondaryColor: '#6B6B6B',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    description: 'Dreamy and golden',
    fontFamily: "'EB Garamond', Georgia, serif",
    fontSize: '1.5rem',
    fontWeight: '400',
    lineHeight: '1.6',
    fontStyle: 'normal',
    letterSpacing: '0.01em',
    textAlign: 'center',
    backgroundColor: '#FFB347',
    backgroundGradient: 'linear-gradient(135deg, #FFB347 0%, #FF6B9D 50%, #C651C9 100%)',
    textColor: '#FFFFFF',
    secondaryColor: '#FFE5D9',
  },
  minimalistDark: {
    id: 'minimalistDark',
    name: 'Minimal Dark',
    description: 'Stark and dramatic',
    fontFamily: "'Inter', system-ui, sans-serif",
    fontSize: '1.25rem',
    fontWeight: '300',
    lineHeight: '1.7',
    fontStyle: 'normal',
    letterSpacing: '0.03em',
    textAlign: 'center',
    backgroundColor: '#000000',
    textColor: '#FFFFFF',
    secondaryColor: '#8E8E8E',
  },
}

export const themeList = Object.values(themes)
